version: '3.8'
services:
  dev:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: fobework-interview-api
    restart: always
    ports:
        - 5000:5000
    depends_on:
       - postgres
    env_file:
        - .env
    networks:
        - fobework-interview-network

  postgres:
    image: postgres:13-alpine
    container_name: postgres-fobework-interview
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - fobework-interview-network

volumes:
  postgres:
    name: fobework-interview-docker-db

networks:
  fobework-interview-network:

